### ISSUE TITLE
Time Multiplier CV Input Affecting Both AFG's

### ISSUE THREAD

**Issue by DARKSPARKLER** [wir35/marf#28]
This is an issue that I found during the first cycle of firmware updates a couple years ago, but I forgot to check for it until now. 

When I apply CV into the Time Multiplier CV input on AFG one, I find that it will also affect the timing of AFG 2, and vice versa when patched the other way around. The CV doesn't have as dramatic of an affect on the adjacent AFG as it does to the one it's meant to control, but it is very noticeable when set to extreme settings. 

Here's a video showing off the problem: https://www.youtube.com/watch?v=IWDBIvLFyv0 

Thanks, and chime in to let me know if you are having the same issue!

**Comment by norjad** [comment]
Yes, I can confirm this. SAModular hardware, latest revision.

The influence is much stronger in the negative range of the CV input scaling knob, but it's similar in your video. Might be a hardware issue indeed. A case for Dave Brown?

**Comment by maxl0rd** [comment]
I will look into this. I strongly suspect this could be a hardware problem.

**Comment by maxl0rd** [comment]
According to Dave Brown, this is caused by overvoltage at the mux IC that switches the time multipliers and the stage address signals to the micro.

In practice, avoid this by not exceeding 100% time multiplier modulation on any channel. For example, if you have the time multiplier pot at 50%, don't send more than 5v to the cv input. Exceeding ~10v ish causes all the other CVs to become unstable. A real solution is to replace the large number of diodes with a more appropriate part.

_The solution is to use Schottky diodes such as the SD103B in place of all the 1N457 diodes. This limits the over voltage to within specifications. Over voltage can be avoided by keeping the CV input to 10V or less and not adding in more control to exceed a 10V summation._
