### ISSUE TITLE
Interval time sliders do not save

### ISSUE THREAD

**Issue by maxl0rd** [wir35/marf#4]
Interval Time sliders do not save. From what I hear, v1 allows you to save both the Output Voltage sliders and the Interval Time sliders but v2 does not. Robert Standefer looked through the code and confirmed that it was never implemented.

https://www.muffwiggler.com/forum/viewtopic.php?f=19&t=223061

**Comment by stevenbarsky** [comment]
Reminder to self. Self, this may be related to the issue with improper mapping of the config dip switches.Dave Brown has already noted that the Voltage range DIP switches functionally do not match the screening on the circuit board. This may be related.

**Comment by stevenbarsky** [comment]
Settings were being saved and recalled. When preset was loaded there was no "wait until slider value catches-up to recalled value" code being applied to the time interval slider data, so as soon as the preset was recalled, the values were immediately overwritten by the current value of the slider. Fixed by Guy. v2.5b3
